name: Documentation
on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: setup directories for Jekyll build
        run: |
          rm -rf _site
          sudo chmod -R 777 .
          
      - name: Jekyll build
        uses: docker://hamelsmu/notes
        with:
          args: bash -c "gem install bundler && jekyll build -V --strict_front_matter --trace"
        env:
          JEKYLL_ENV: 'production'

      - name: copy CNAME file into _site if CNAME exists
        run: |
          sudo chmod -R 777 _site/
          cp CNAME _site/ 2>/dev/null || :

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_dir: ./_site
